server:
  port: 11013
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam
    username: root
    password: root
#    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: '在线考试'
    version: 1.0
